### ISSUE TITLE
Cannot find "null" module on browser version since v0.5.0

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#41]
I got the following error since V0.5.0 where was introduced rdflib@0.20.1 (with solid-file-cli as webpack : externals refered as "null" module for browser usage (same being applied to solid-file-client))
```
Error: Cannot find module 'null' from '/volume1/homes/admin/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server/node_modules/solid-file-client/dist/browser'
```
At the same time I tried to upgrade `solid-ide` to use latest version of `solid-file-client`. The solid-file-client never loaded.

**Comment by jeff-zucker** [comment]
It must be a difference in our development environments, because if I clone the current master, then run npm install, it successfully builds and I can access it from the created bundle.js.  I checked this before I npm'd it and also just now.

**Comment by bourgeoa** [comment]
I found that `webpack npm null-loader` could replace an **unused module by an empty module**.
After a lot of trial and error, I found a working solution : 
. as rdflib treated solid-file-cli as external and only succeed any compile keeping it external
. I added a rule to use `webpack null loader` but it only compiled if 
. in external I used `"solid-file-client" : "solid-file-client"` in replacement of `"solid-file-client" : "null"` .

With that I have a solid-ide and solidTiddlywiki both using a solid-file-client compatible with rdflib@0.20.1

**Comment by jeff-zucker** [comment]
I have never seen the error you describe.  If it is indeed a problem with how rdflib external works, then I need to fix it there, we should not be doing things to solve an error that occurs elsewhere.  But, as I said, I do not get the same error as you - I have never seen that error.

**Comment by bourgeoa** [comment]
Here are the 2 webpack files I modified

[webpack.zip](https://github.com/jeff-zucker/solid-file-client/files/3188913/webpack.zip)

**Comment by bourgeoa** [comment]
The developpement environnement for solidTiddliwiki is `browserify babelify`
For solid-ide there is no dev environnement as you only use <script> with CDN or directly a solid-file-client.bundle.js produced by solid-file-client compile.

I will test a rdflib compile using the null-loader (external for solid-file-cli may not be needed - just replaced by "null") and see what is the impact on solid-file-client. Need to add null- loader to package.json

**Comment by jeff-zucker** [comment]
I suggest you look at what versions of node and npm you are running and make sure that you do not have global installs of the development modules.  I've done that on my end and the build continues to work with solid-auth-cli set to "null" in solid-file-client's externals and no use of null-loader.

**Comment by jeff-zucker** [comment]
I am using node v10.15.3 LTS and node 6.9.0 on Linux.

**Comment by jeff-zucker** [comment]
And webpack-cli v3.2.1

**Comment by jeff-zucker** [comment]
I just tested again.  These two commands produce a working bundle for me:
```
git clone https://github.com/jeff-zucker/solid-file-client.git
cd solid-file-client
npm install
```

**Comment by bourgeoa** [comment]
I have node v8.9.4 and npm 5.6.0 on synology linux old compared to yours.
I think you find the point.
I just verified solid-ide with solid-file-client is working with v0.5.1 that you build and not with v0.5.0 I build
I shall see if I can upgrade npm and nodjs

**Comment by bourgeoa** [comment]
no possible upgrade on synology but created nodejs 10.15.3 and npm 6.0.9 on ubuntu linux on windows.
solid-file-client  with rdflib 0.20.1 build OK.
With the new build solid-file-client : 

-  my solid-ide with solid-file-client is OK

- my solidTiddlywiki build still fails with the same error 
```
> @ build /mnt/c/users/alain/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server
> browserify --standalone _ main.js -o ../nodesolidserver/main.js -t babelify && cp about.tid config.tid plugin.info ../nodesolidserver/

[BABEL] Note: The code generator has deoptimised the styling of /mnt/c/users/alain/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server/scripts/solid-file-client.bundle.js as it exceeds the max of 500KB.
Error: Cannot find module 'null' from '/mnt/c/users/alain/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server/scripts'
```

- I tried with the npm solid-file-client v.0.5.1 you compiled and same error

```
> @ build /mnt/c/users/alain/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server
> browserify --standalone _ main.js -o ../nodesolidserver/main.js -t babelify && cp about.tid config.tid plugin.info ../nodesolidserver/

Error: Cannot find module 'null' from '/mnt/c/users/alain/TW5/plugins/bourgeoa/tiddlywiki-node-solid-server/node_modules/solid-file-client/dist/browser'```

**Comment by bourgeoa** [comment]
I am using the latest version of browserify 16.2.3 and babelify 10.0.0

**Comment by jeff-zucker** [comment]
Is it possible for you to use something like null-loader in tiddlywiki?  I think solid-file-client should behave in a webpack way and should be usable with webpack without any special instructions just as rdflib and solid-auth-client are.  If it's possible to use it with browserify with a small modification in the package using browserify, then I would opt for that and the readme can just warn developers that if they use browserify, there's an extra step.  Does that seem right to you?  One other possibility is that I have done something wrong in solid-auth-cli.  Currently there's a blank index.js in the browser folder and maybe that file should not be there.  Could you try to a) npm install solid-file-client, b) delete that file in the node_modules of the solid-file-client build c) try to use the resulting bundle in tiddlywiki.  If that works, I'll delete the file from the solid-auth-cli build.

**Comment by bourgeoa** [comment]
I was in the same line than you and there is a simple way not to load the "null" module in browserify, you just add `browserify -i null` (-i for **ignore**). My script is now : 

> `  "scripts": {
    "build": "browserify -i null --standalone _ main.js -o ../nodesolidserver/main.js -t babelify && cp about.tid config.tid plugin.info ../nodesolidserver/"

clearly the read.me should warn the developpers using browserify to add **-i null**

**Comment by bourgeoa** [comment]
I reopened the issue to solve the problem uncon=untered in react https://gitter.im/solid/app-development?at=5cf02976481ef4167ba24de1

I see 2 ways to explore : 
- test use the use of the null-loader as I have allready tested
- explore the use of the webpack WrapperPlugin module (https://github.com/levp/wrapper-webpack-plugin), allready used by rdflib.js, and creating 2 webpack files (one for browser without solid-auth-cli and the other one with it)

here is what rdflib.js does : 

> const path = require('path')
> const WrapperPlugin = require('wrapper-webpack-plugin');
> 
> module.exports = (env, args) => {
>   return {
>     mode: 'production',
>     entry: [
>       './src/index.js'
>     ],
>     output: {
>       path: path.join(__dirname, '/dist/'),
>       filename: 'rdflib.min.js',
>       library: '$rdf',
>       libraryTarget: 'umd'
>     },
>     module: {
>       rules: [
>         {
>           test: /\.js$/,
>           loader: 'babel-loader',
>           exclude: /node_modules/
>         }
>       ]
>     },
>     plugins: [
>       new WrapperPlugin({
>         // Fall back to window.fetch when solid-auth-client is not present,
>         // so rdflib.js can still work outside of Solid
>         header: `if (typeof window !== 'undefined') {
>                    if (!window.solid)
>                      window.solid = {}
>                    if (!window.solid.auth)
>                      window.solid.auth = { fetch: (a, b) => window.fetch(a, b) }
>                  }`
>       })
>     ],
> 

I suppose the second option implies to modify rdflib.js.
Then we remain with the first option. I shall make a test

**Comment by bourgeoa** [comment]
The null-loader solution works in react-solid.
I had a very bad trip to find a way to test the new version without pushing to npm
https://forum.solidproject.org/t/react-solid-use-of-require-from-npm-or-from-react-solid/1875

**Comment by jeff-zucker** [comment]
Is this solved now with your recent work @bourgeoa?  If so, please close.

**Comment by Otto-AA** [comment]
I'd suggest to keep the issues open until the fix is released. On the one hand, people who also encounter this issue will know that it is still not fixed, and on the other hand if we make more changes to the other branch in the meantime it could happen that the fix somehow gets removed. Therefore I#d suggest checking right before the release and closing afterwards.

**Comment by jeff-zucker** [comment]
Very good points. I agree.

**Comment by jeff-zucker** [comment]
v1.0.0 is on npm. Can you check if this is fixed and close it if so.

**Comment by jeff-zucker** [comment]
@bourgeoa  - Should this issue still be open?
